on:
  push:
    branches:
      - master
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install pipenv
      - run: python -m pipenv install --skip-lock --dev
      # see:
      # - Unexpected type '' encountered while reading 'action manifest root' · Issue #577 · paambaati/codeclimate-action
      #   https://github.com/paambaati/codeclimate-action/issues/577#issuecomment-1188527480
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: python -m pipenv run inv coverage --xml
